const chinese = {
  success: "成功",
  hello: "你好",
  guest: "客人",
  signIn: "登入",
  signOut:"登出",
  signUp: "報名",
  emailOrMobileNumber: "电子邮件或手机号码",
  password: "密码",
  enterYouremail: "输入你的电子邮箱",
  byContinueYouAgreeToAmazonCondition:
    "继续，即表示您同意亚马逊的使用条件和隐私声明。",
  newToAmazon: "亚马逊新手？",
  createYourAmazonAccount: "创建您的亚马逊账户",
  selectYourAddress: "选择您的地址",
  helloGuest:"你好客人",
  youHaveBeenLoggedOutSucessfully:"您已成功註銷!",
  okay:"好的",
  returns:"退貨",
  orders:"＆命令",
  cart:"大車",
  conditionOfUse:"使用條件",
  and:"和",
  privacyNotice:"隱私聲明",
  help:"幫助",
  AmazoncomIncoritsAffiliates:"© 1996-2022，Amazon.com, Inc. 或其附屬公司",
  enterYourPassword: "輸入您的密碼",
  enterYourName: "輸入你的名字",
  enterYourNameMaxLength: "輸入您的姓名（最多10個字符）",
  alreadyaMember:"已經是會員？",
  inStock:"有存貨",
  giftOptionsNotAvailable:"禮品選項不可用",
  learnMore:"了解更多",
  quantity:"數量：",
  deleteItemFromCart:"從購物車中刪除商品",
  yourAmazonCartIsEmpty:"您的亞馬遜購物車是空的",
  showProducts:"展示產品",
  ShoppingCart: "購物車",
  subTotal:"小計",
  items:"項目",
  clearCart:"清除購物車",
  thePriceAndAvailabilityOfItem:"Amazon.in 商品的價格和可用性可能會發生變化。購物車是存儲商品列表的臨時位置，並反映每件商品的最新價格。你有促銷代碼嗎？付款時，我們會要求您輸入索賠代碼。",
  yourOrderEligibleForFreeDelivery:"Your Order Eligible For Free Delivery",
  selectThisOptionAtCheckout:"您的訂單符合免費送貨條件",
  details:"細節",
  continueShopping:"繼續購物",

};

export default chinese;
