const english = {
  success: "Success",
  hello: "Hello",
  guest: "Guest",
  signIn: "Sign in",
  signOut:"Sign out",
  signUp: "Sign up",
  emailOrMobileNumber: "Email or mobile phone number",
  password: "Password",
  enterYouremail: "Enter your email",
  byContinueYouAgreeToAmazonCondition:
    "By continuing, you agree to Amazon's Conditions of Use and Privacy Notice.",
  newToAmazon: "New to Amazon?",
  createYourAmazonAccount: "Create your Amazon account",
  selectYourAddress: "Select your address",
  helloGuest:"Hello Guest",
  youHaveBeenLoggedOutSucessfully:"You Have Been Loggged Out Sucessfully!",
  okay:"Okay",
  returns:" Returns ",
  orders:"& Orders",
  cart:"Cart",
  conditionOfUse:"Conditions of Use",
  and:"And",
  privacyNotice:"Privacy Notice",
  help:"Help",
  AmazoncomIncoritsAffiliates:" © 1996-2022, Amazon.com, Inc. or its affiliates",
  enterYourPassword: "Enter your password",
  enterYourName: "Enter your name",
  enterYourNameMaxLength: "Enter your name ( Max length is 10 characters )",
  alreadyaMember:"Already a Member?",
  inStock:"In Stock",
  giftOptionsNotAvailable:"Gift Options Not Available",
  learnMore:"Learn More",
  quantity:"Quantity:",
  deleteItemFromCart:"Delete Item From Cart",
  yourAmazonCartIsEmpty:"Your Amazon Cart is empty",
  showProducts:"Show Products",
  ShoppingCart: "Shopping Cart",
  subTotal:"Sub Total",
  items:"Items",
  clearCart:"Clear Cart",
  thePriceAndAvailabilityOfItem:" The price and availability of items at Amazon.in are subject to change. The shopping cart is a temporary place to store a list of your items and reflects each item's most recent price. Do you have a promotional code? We'll ask you to enter your claim code when it's time to pay.",
  yourOrderEligibleForFreeDelivery:"Your Order Eligible For Free Delivery",
  selectThisOptionAtCheckout:"Select this Option At Checkout",
  details:"Details",
  continueShopping:"Continue Shopping",


  

};

export default english;
