const vietnam = {
    success: "thành công",
    hello: "Xin chào",
    signIn: "đăng nhập",
    signOut:"đăng xuất",
    signUp: "đăng ký",
    emailOrMobileNumber: "email hoặc số điện thoại di động",
    password: "mật khẩu",
    enterYouremail: "Nhập email của bạn",
    byContinueYouAgreeToAmazonCondition:
      "Bằng cách tiếp tục, bạn đồng ý với Điều kiện sử dụng và Tuyên bố về quyền riêng tư của Amazon.",
    newToAmazon: " Mới đến Amazon?",
    createYourAmazonAccount: "Tạo tài khoản Amazon của bạn",
    selectYourAddress: "chọn địa chỉ của bạn",
    helloGuest:"xin chào Khách",
    youHaveBeenLoggedOutSucessfully:"Bạn đã đăng xuất thành công!",
    okay:"được rồi",
    returns:"trả lại",
    orders:"&đơn đặt hàng",
    cart:"xe đẩy",
    conditionOfUse:"Điều kiện sử dụng",
  and:"Và",
  privacyNotice:"Thông báo về quyền riêng tư",
  help:"giúp đỡ",
  AmazoncomIncoritsAffiliates:"© 1996-2022, Amazon.com, Inc. hoặc các chi nhánh của nó",
  enterYourPassword: "nhập mật khẩu của bạn",
  enterYourName: "Nhập tên của bạn",
  enterYourNameMaxLength: "Nhập tên của bạn (Độ dài tối đa là 10 ký tự)",
  alreadyaMember:"Đã là thành viên hay chưa?",
  inStock:"Trong kho",
  giftOptionsNotAvailable:"Tùy chọn quà tặng không khả dụng",
  learnMore:"Tìm hiểu thêm",
  quantity:"Số lượng:",
  deleteItemFromCart:"Xóa Hàng Khỏi Giỏ Hàng",
  yourAmazonCartIsEmpty:"Giỏ hàng Amazon của bạn trống",
  showProducts:"Hiển thị sản phẩm",
  ShoppingCart: "Giỏ hàng",
  subTotal:"Tổng phụ",
  items:"Mặt hàng",
  clearCart:"Dọn dẹp giỏ hàng",
  thePriceAndAvailabilityOfItem:"Giá cả và tính sẵn có của các mặt hàng tại Amazon.in có thể thay đổi. Giỏ hàng là nơi tạm thời để lưu trữ danh sách các mặt hàng của bạn và phản ánh giá gần đây nhất của từng mặt hàng. Bạn có một mã khuyến mại? Chúng tôi sẽ yêu cầu bạn nhập mã yêu cầu khi đến lúc thanh toán.",
  yourOrderEligibleForFreeDelivery:"Đơn hàng của bạn đủ điều kiện để giao hàng miễn phí",
  selectThisOptionAtCheckout:"Chọn tùy chọn này khi thanh toán",
  details:"Chi tiết",
  continueShopping:"Tiếp tục mua sắm",

  };
  
  export default vietnam;
  